version: "3.8"

services:
  db:
    image: mysql:8.1.0
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network
    profiles:
      - prod
    depends_on:
      - app-prod

  app-dev:
    build:
      context: ./app
    env_file:
      - ./app/.env
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - dev

  app-prod:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file:
      - ./app/.env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - prod

networks:
  app-network:
    driver: bridge

volumes:
  db_data: